(function(){
  var firebaseConfig={apiKey:'AIzaSyAzipXgpdZERMXyDXUyu5Wisglob-khhRI',authDomain:'gestaoconcept-d456d.firebaseapp.com',projectId:'gestaoconcept-d456d',storageBucket:'gestaoconcept-d456d.firebasestorage.app',messagingSenderId:'729487656186',appId:'1:729487656186:web:0d80c92e040ce466ffb543'};
  var auth,db,remoteLoading=false,authBusy=false;
  function show(id,on){var e=document.getElementById(id);if(e)e.hidden=!on;}
  function msg(t){var e=document.getElementById('authMessage');if(e)e.textContent=t;}
  function authError(err){if(err&&err.code==='auth/configuration-not-found')return 'Ative E-mail/senha no Firebase: Authentication > Sign-in method.';if(err&&err.code==='auth/too-many-requests')return 'Aguarde alguns segundos antes de tentar novamente.';return 'E-mail ou senha incorretos. Aguarde alguns segundos e tente novamente.';}
  function localMode(t){show('authScreen',false);show('appContent',true);msg(t||'Modo local ativo.');}
  async function loadRemote(user){remoteLoading=true;msg('Carregando seus registros…');try{var read=db.collection('roletaUsers').doc(user.uid).get();var snap=await Promise.race([read,new Promise(function(_,reject){setTimeout(function(){reject(new Error('timeout'));},5000);})]);if(snap.exists&&snap.data().state)window.RoletaRecords.replaceState(snap.data().state);msg('Conectada como '+(user.email||'Evelyn')+'. Registros sincronizados.');show('authScreen',false);show('appContent',true);}catch(e){localMode('Acesso confirmado. A roleta está pronta; a sincronização será retomada quando o banco responder.');}remoteLoading=false;}
  async function sync(){if(!db||remoteLoading)return;var user=auth.currentUser;if(!user)return;try{await db.collection('roletaUsers').doc(user.uid).set({state:window.RoletaRecords.getState(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});}catch(e){}}
  function boot(){if(!window.RoletaRecords||!window.firebase){localMode();return;}try{firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();}catch(e){localMode();return;}auth.onAuthStateChanged(function(user){if(user){show('authScreen',false);show('appContent',true);msg('Acesso confirmado.');loadRemote(user);}else{show('authScreen',true);show('appContent',false);}});document.getElementById('openLocal').addEventListener('click',function(){localMode('Modo local ativo. Registros salvos neste aparelho.');});document.getElementById('authForm').addEventListener('submit',async function(e){e.preventDefault();if(authBusy)return;authBusy=true;var email=document.getElementById('authEmail').value.trim(),pass=document.getElementById('authPassword').value;msg('Entrando…');try{await Promise.race([auth.signInWithEmailAndPassword(email,pass),new Promise(function(_,reject){setTimeout(function(){reject(new Error('timeout'));},7000);})]);}catch(err){msg(err.message==='timeout'?'O servidor demorou. A roleta será aberta neste aparelho.':authError(err));if(err.message==='timeout')localMode();}setTimeout(function(){authBusy=false;},2200);});document.getElementById('createAccess').addEventListener('click',async function(){if(authBusy)return;authBusy=true;var email=document.getElementById('authEmail').value.trim(),pass=document.getElementById('authPassword').value;if(!email||!pass||pass.length<6){msg('Digite o e-mail e uma senha com pelo menos 6 caracteres.');authBusy=false;return;}msg('Criando acesso…');try{await Promise.race([auth.createUserWithEmailAndPassword(email,pass),new Promise(function(_,reject){setTimeout(function(){reject(new Error('timeout'));},7000);})]);}catch(err){msg(err.message==='timeout'?'O servidor demorou. A roleta será aberta neste aparelho.':(err.code==='auth/email-already-in-use'?'Este e-mail já tem acesso. Aguarde 2 segundos e use Entrar.':authError(err)));if(err.message==='timeout')localMode();}setTimeout(function(){authBusy=false;},2200);});document.getElementById('logoutCloud').addEventListener('click',function(){auth.signOut();});['saveLater','finishEvaluation','videoReceived'].forEach(function(id){var e=document.getElementById(id);if(e)e.addEventListener('click',function(){setTimeout(sync,300);});});document.getElementById('spinBtn').addEventListener('click',function(){setTimeout(sync,5000);});document.getElementById('resetCycle').addEventListener('click',function(){setTimeout(sync,500);});}
  window.addEventListener('load',boot);
})();
